name: tut_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6
  retrofit: ^3.0.1+1
  analyzer: ^5.2.0
  dio: ^4.0.6
  json_serializable: ^6.5.4
  retrofit_generator: ^4.1.2
  build_runner: ^2.3.2

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/splash_logo.png
    - assets/images/onBoarding_logo1.svg
    - assets/images/onBoarding_logo2.svg
    - assets/images/onBoarding_logo3.svg
    - assets/images/onBoarding_logo4.svg
    - assets/images/left_arrow_ic.svg
    - assets/images/right_arrow_ic.svg
    - assets/images/solid_circle_ic.svg
    - assets/images/hollow_circle_ic.svg

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600